#!/usr/bin/env python
import os

Import('*')

sources = Glob("*.cpp") # glob root directory

# recursively glob subdirectories
for root, dirnames, filenames in os.walk('.'):
    for dirname in dirnames:
        sources = sources + (Glob(os.path.join(root, dirname, "*.cpp")))


# create and return the default target

default_target = None

if env["platform"] == "macos":
    default_target = env.SharedLibrary(
        "libssp.{}.{}.framework/libssp.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    default_target = env.SharedLibrary(
        "libssp{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Return("default_target")
